name: Todo-app

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x] #  write here your project node version 

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Specify the npm version compatible with your Node.js version
          npm: '8.19.4'  # Adjust if needed for project compatibility
          cache: 'npm'
      - run: npm install -g npm@8.19.4  # Likely unnecessary with actions/setup-node
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci --no-progress
      - run: npm run build --if-present
      - run: pm2 restart todo
